[SGTM bugs] let due_on handle nulls and add more test (#182)
### Summary

- Occassionally seeing errors of the type: 
```
  File "/var/task/src/handler.py", line 25, in handle_github_webhook
    http_response = github_webhook.handle_github_webhook(event_type, github_event)
  File "/var/task/src/github/webhook.py", line 195, in handle_github_webhook
    return _events_map[event_type](payload)
  File "/var/task/src/github/webhook.py", line 167, in _handle_check_suite_webhook
    github_controller.upsert_pull_request(pull_request)
  File "/var/task/src/github/controller.py", line 30, in upsert_pull_request
    asana_controller.update_task(
  File "/var/task/src/asana/controller.py", line 39, in update_task
    else _new_due_on_or_none(task, update_task_fields)
  File "/var/task/src/asana/controller.py", line 55, in _new_due_on_or_none
    if task["due_on"] >= today:
TypeError: '>=' not supported between instances of 'NoneType' and 'str'
```
- this just adds a null check. This happens if the due date is purposefully removed (someone decides they won't follow up with the PR for a long time)

Asana tasks:


Relevant deployment: 

CC: @prebeta @michael-huang87 @suzyng83209 @vn6

### Test Plan

- tests pass

### Risks



Pull Request: https://github.com/Asana/SGTM/pull/182



Pull Request synchronized with [Asana task](https://app.asana.com/0/0/1207270260114936)